  version: '3.8'

  services:
    postgres:
      image: postgres
      container_name: my_db
      environment:
        POSTGRES_DB: extrahot
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
      networks:
        - springnet


    springboot-app:
      build: .
      container_name: my_springboot
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/extrahot
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 1234
      ports:
        - "8080:8080"
      networks:
        - springnet

  volumes:
    pg_data:

  networks:
    springnet: